services:
#  fastapi:
#    build: .
#    ports:
#      - "8000:8000"
  postgres:
    image: "postgres:17.5-bookworm"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres